#+title: A bit

* What is this?

This is a work-in-progress blog for some programming and math stuff.
I will upload things every now and then.

* Who am I?

I am Gonzalo Juarez.  I like some kinds of math and some kinds of
programming.  Most of the programming I do is in C++, although I take
heavy influences from other languages and programming paradigms.

** Contact

Reach out via [[mailto:gonzalojuarezte@gmail.com][email (gonzalojuarezte@gmail.com)]] or [[https:linkedin.com/in/gonzalo-juarez-tello-435bb5364][linkedin]] for any
questions, corrections, discussions, or comments related to the blogs'
contents.

* Blog Index

This should be populated some day...

[[file:dynamic-dispatch-and-pairings-of-natural-numbers/main.org][State machines, dynamic multi-dispatch, and pairings of natural numbers]]

* Generative AI on this site

All the words, code, math and their mistakes in this site are written
by me.  Usage of generative AI is limited to some of the scripts used
to draw plots --- sometimes I'm lazy.


