#+options: ^:nil
#+title: State machines, dynamic multi-dispatch, and pairings of natural numbers

Recently at work I had to write a state machine in C++20. At the
expense of being redundant given the target audience of this post, let
us recall that a state machine evolves over time by changing its
internal state each time it is fed some input. Having to execute some
logic based on /both/ the current state and the input being fed
implies implementations must use some kind of /dynamic multi-dispatch/
technique.


In C++ there are well-known approaches to do this using =std::variant=
and =std::visit= (see [[https://khuttun.github.io/2017/02/04/implementing-state-machines-with-std-variant.html][Kalle Huttunen's post]], [[https://github.com/mpusz/fsm-variant][Mateusz Pusz's library]],
or similar).  It is also possible to implement with inheritance-based
dynamic polymorphism using something like the visitor pattern.  The
problem is that due to circumstances of life and past decisions (of my
authoring) the dispatch mechanism must not be based on types, but
based on =enum= values.


Using some mathematical and metaprogramming tricks the problem can be
solved and even extended to work for the n-ary case --- maybe not
something I'd recommend if compilation times are of any concern at
all, but I found this cool anyways.


* The problem setup

In order to have something concrete in mind, we will use the finite
state machine (FSM) described by the following transition table

| State\Event   | a | b | c |
|---------------+---+---+---|
| A (initial)   | A | B | C |
| B             | B | C | D |
| C             | C | B | D |
| D (final)     | - | - | - |

where '-' is used to indicate that there are no transitions from
state-input pair at all and we consider that to be an error.  We could
make instead an error state and have several final states, that would
not affect our multi-dispatch solution so let us not waste time in the
finer semantic details of the FSM.

The =enum= types for this state machine are defined as follows

#+include: ./code/basic.cpp src c++ :lines "153-155"

A naive solution can make use of nested conditionals to choose a
behavior based on the value of state and input:

#+BEGIN_SRC
  switch (state) {
  case states::A:
    switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case states::B:
      switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case states::C:
      switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case states::D:
      switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case default: __builtin_unreachable();
  }
#+END_SRC

But this has a couple of issues:

1. **Maintainability**: These =enum= have few values in their range.
   My practical case would not fit as nicely in the page nor the code
   would be as easy to follow.  Regardless, my initial solution was
   this simple, and I found it was not only hard to read, but also it
   made some other trade-offs which ended up introducing some
   technical debt (maybe just a skill-issue of mine).

2. **Double jumps**: Here we do not have one sole jump, but rather
   two!  First there is a jump based on =state=, then there is a jump
   based on =input=. My hypothesis is that this is potentially
   problematic for the CPU and the compiler:

   - For the CPU: The extra branching by itself may not be that much
     of an issue on some modern CPUs as long as the transition
     patterns are [[https://lemire.me/blog/2026/03/18/how-many-branches-can-your-cpu-predict/][predictible]]. However, the double jump may be
     problematic to the instruction cache (the intermediate =case=
     blocks may be too far apart, e.g. due to =-malign-labels=), or
     make inefficient use of the instruction fetch unit (e.g. Skylake
     fetches 16 bytes per cycle).

   - <<switch-lowering>> /"Huh, but the compiler will surely optimize away the nesting"/:
     It turns out compilers are not that good at optimizing nested
     switches --- check this simple example on [[https://godbolt.org/z/7zb8YbesW][Compiler Explorer and
     GCC 11.2]].  What switches compile to depends on [[https://youtu.be/gMqSinyL8uk][a lot of stuff]], in
     particular the distribution of the values of the cases seems to
     be very relevant: having a dense distribution of values when
     there is a large number of cases encourages the compiler to
     generate /jump tables/ (otherwise it resorts to other trickery,
     such as binary searches). I am not a /connoisseur of switch
     lowering/, nor pretending to be, I just stick with "compiler not
     good at nested. Dense cases imply jump table imply success".

So now we will try to come up with something nicer, which requires a
single jump and provides some improvement in maintainability by
generating the jump table automatically at compile time --- although
some would argue the resulting template metaprogramming becomes the
new maintainability burden, a valid point.

* The math

Summarizing, we need to convert the double jump caused by a nested
=switch= into a single jump. Each =case= label is associated to *one*
=integral= value. A double jump therefore requires *two* =integral=
values to dispatch. Therefore we need to

1. *convert* /two =integral= values into one =integral= value/, and

2. this must be done *at compile time* (since the value must be
   associated to a =case= label), and

3. we need to *convert back* /one =integral= value into two =integral=
   values/, and

4. this must also be done *at compile time* because we want to use the
   chosen integral values to perform /static/ dispatch (say, as
   =std::integral_constant= tags).

For this section we leave the compile time requirements aside and deal
with the converting to and back from one =integral= to two =integral=
values.  Moreover, we will restrict the problem to /unsigned/
=integral= values. This screams [[https://en.wikipedia.org/wiki/Pairing_function][pairing function]]!


As a one-paragraph-context for those not familiarized with the
concept: a pairing function is an invertible function (a bijection)
between the set of natural numbers ($\mathbb{N}$) and the set of pairs
of natural numbers ($\mathbb{N} \times \mathbb{N}$).  Pairing
functions are used, for example, to demonstrate that $\mathbb{N}$ and
$\mathbb{N} \times \mathbb{N}$ have the same "size" --- an unintuitive
result at first because a finite set does not have a pairing function
with its corresponding set of pairs. But things become odd when sets
are infinite, and that is perfectly natural (pun intended).


There are [[https://drhagen.com/blog/superior-pairing-function/][many pairing functions]], I considered the following:

- Pairing based on the [[https://en.wikipedia.org/wiki/Fundamental_theorem_of_arithmetic][Fundamental Theorem of Arithmetic]]. This pairing
  function uses the fact that any integer greater than $1$ has a
  unique representation as a product of powers of primes.  Such a
  pairing $f$ can be defined as

  \[
     f : \mathbb{N} \times \mathbb{N} \to \mathbb{N},\quad f(a,b) := 2^a 3^b.
  \]

  After staring at the definition of $f$ for a while, it is clear that
  we cannot use this pairing for at least two reasons:

  - First, the range of $f$ is too sparse. Two numbers in the range of
    $f$ have a gap between them of at least a factor of $2$ between
    them.  This is likely to have a [[switch-lowering][negative effect on the code
    generated]] for the =switch= whose labels correspond to a subset of
    the range of $f$.

  - The second problem has to do with the finite nature of computers.
    In computers we do not work with $\mathbb{N}$, but with
    =std::uint64_t= at best (leaving =BigInt= out of the question, we
    are doing #performance). Trouble would arise when the sum of the
    =enum= values $a$ and $b$ being mapped is equal to or greater than
    $64$, because

      \[ f(a,b) \geq 2^a3^b \geq 2^{a+b} \gt 2^{64}-1 \]

    overflows =std::uint64_t=!

  (For those interested in the inverse $f^{-1}$, I recommend the
  introductory chapters on recursive functions in [[https://www.cambridge.org/core/books/computability-and-logic/440B4178B7CBF1C241694233716AB271][Computability and
  Logic by Boolos, Burgess, & Jeffrey 5th ed]])

- The [[https://en.wikipedia.org/wiki/Pairing_function#Cantor_pairing_function][Cantor pairing function]] is historically the first pairing
  function (as far as I know). It can be visualized in the a 2D graph
  as a walk through the diagonals of the graph.

  #+CAPTION: Cantor pairing function (image from [[https://drhagen.com/blog/superior-pairing-function/][drhagen's blog]])
  #+NAME: fig:cantor_pairing
  [[file:img/cantor_pairing_light.svg]]

  Sort of by inspection you can tell the Cantor pairing function is
  not as overflow prone as the one based on the Fundamental Theorem of
  Arithmetic (the gap between subsequent steps of the walk does not
  increase by powers of $2$). However --- as shown in [[https://www.vertexfragment.com/ramblings/cantor-szudzik-pairing-functions/][this blog that
  does a much better job than I can at explaining the sparsity of the
  function]] --- even for the set $S := \{(x, y) \in \mathbb{N} \times
  \mathbb{N} : x, y \lt 10 \}$ we get lots of gaps in the subset of
  the range of the Cantor function corresponding to $S$.  We can do
  much better.

- The [[http://szudzik.com/ElegantPairing.pdf][Szudzik pairing function]] is relatively recent, given that the
  last two entries were from the 1800s and the beginning of 1900s. It
  too can be visualized as a walk through a graph, but this time the
  walk follows the sides of increasingly larger squares.

  #+CAPTION: Szudzik pairing function (image from [[https://drhagen.com/blog/superior-pairing-function/][drhagen's blog]])
  #+NAME: fig:cantor_pairing
  [[file:img/szudzik_pairing_light.svg]]

  The approach of Szudzik achieves a very dense range (as shown in the
  aforementioned [[https://www.vertexfragment.com/ramblings/cantor-szudzik-pairing-functions/][blog]] entry), which is perfect for our needs.

So we will go with Szudzik's approach, whose formulas read

\begin{equation*}
  s(x, y) :=
  \begin{cases}
  y^2 + x &\text{if } y \ge x\\
  x^2 + x + y&\text{otherwise}
  \end{cases}
\end{equation*}

and its inverse

\begin{equation*}  
 s^{-1}(z) :=
   \begin{cases}
  (z - (\lfloor \sqrt{z} \rfloor)^2, \lfloor \sqrt{z} \rfloor) &\text{if } z - (\lfloor \sqrt{z} \rfloor)^2 < \lfloor \sqrt{z} \rfloor \\
  (\lfloor \sqrt{z} \rfloor, z - (\lfloor \sqrt{z} \rfloor)^2 - \lfloor \sqrt{z} \rfloor) &\text{otherwise}
  \end{cases}.
\end{equation*}  

This is implemented in C++20 as
follows

#+include: ./code/basic.cpp src c++ :lines "9-30"

We had to take some care of integer promotion shenanigans using
=std::common_type=, implement an integer square root by hand to keep
things =constexpr= in C++20, and turn the inverse's argument into an
=std::integral_constant= so that it can be computed at compile
time. Now we only need some metaprogramming to glue things together.

* The solution

* Beyond the solution: going variadic

* Conclusion
