#+options: ^:nil
#+title: Dynamic multi-dispatch and pairings of natural numbers

Recently at work I had to write a state machine in C++20. I guess the
target audience already knows this, but for the sake of completeness
let us recall that a state machine evolves over time by changing its
internal state each time it is fed some input. Having to execute some
logic based on /both/ the current state and the input being fed
implies implementations must use some kind of /dynamic multi-dispatch/
technique.


In C++ there are well-known approaches to do this using =std::variant=
and =std::visit= (see [[https://khuttun.github.io/2017/02/04/implementing-state-machines-with-std-variant.html][Kalle Huttunen's post]], [[https://github.com/mpusz/fsm-variant][Mateusz Pusz's library]],
or similar).  I guess it is possible to implement with
inheritance-based dynamic polymorphism using something like the
visitor pattern.  The problem is that due to circumstances of life and
past decisions the dispatch was not based on types but based on =enum=
values.


Using some mathematical and metaprogramming tricks the problem can be
solved --- maybe not something I'd recommend if compilation times are
of any concern at all, but I found this cool anyways.


* The problem setup

To begin, this is the finite state machine (FSM) transition table

| State\Event   | a | b | c |
|---------------+---+---+---|
| A (initial)   | A | B | C |
| B             | B | C | D |
| C             | C | B | D |
| D (final)     | - | - | - |

where '-' is used to indicate that there are no transitions from
state-input pair at all and we consider that to be an error.  We could
make instead an error state and have several final states, that would
not affect our multi-dispatch solution so let us not waste time in the
finer semantic details of the FSM.

The =enum= types for this state machine are defined as follows

#+include: ./code/basic.cpp src c++ :lines "153-155"

A naive solution can make use of nested conditionals to choose a
behavior based on the value of state and input:

#+BEGIN_SRC
  switch (state) {
  case states::A:
    switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case states::B:
      switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case states::C:
      switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case states::D:
      switch (input) {
      case inputs::a: // ...
      case inputs::b: // ...
      case inputs::c: // ...
      case default: __builtin_unreachable();
    }
  case default: __builtin_unreachable();
  }
#+END_SRC

But this has a couple of issues:

1. **Maintainability**: These =enum= have few values in their range.
   My practical case would not fit as nicely in the page nor the code
   would be as easy to follow.  Regardless, my initial solution was
   this simple, and I found it was not only hard to read, but also it
   made some other trade-offs which ended up introducing some
   technical debt (maybe just a skill-issue of mine).

2. **Double jumps**: Here we do not have one sole jump, but rather
   two!  First there is a jump based on =state=, then there is a jump
   based on =input=. My hypothesis is that this is potentially
   problematic for the CPU and the compiler:

   - For the CPU: The extra branching by itself may not be that much
     of an issue on some modern CPUs as long as the transition
     patterns are [[https://lemire.me/blog/2026/03/18/how-many-branches-can-your-cpu-predict/][predictible]]. However, the double jump may be
     problematic to the instruction cache (the intermediate =case=
     blocks may be too far apart, e.g. due to =-malign-labels=), or
     require some extra work from the instruction fetch unit
     (e.g. Skylake fetches 16 bytes per cycle).

   - /"Huh, but the compiler will surely optimize away the nesting"/:
     As it turns out, compilers are not that good at optimizing nested
     switches --- check this simple example on [[https://godbolt.org/z/7zb8YbesW][Compiler Explorer and
     GCC 11.2]].  What switches compile to depends on [[https://youtu.be/gMqSinyL8uk][a lot of stuff]], in
     particular the distribution of the values of the cases seems to
     be very relevant: having a dense distribution of values when
     there is a large number of cases encourages the compiler to
     generate /jump tables/ (otherwise it resorts to other trickery,
     such as binary searches). I am not a /connoisseur of switch
     lowering/, nor pretending to be, I just stick with "compiler not
     good at nested. Dense cases imply jump table imply success".

So now we will try to come up with something nicer, which requires a
single jump and provides some improvement in maintainability by
generating the jump table automatically at compile time (although some
would argue the resulting template metaprogramming becomes the new
maintainability burden, valid point).

* The math

Summarizing, we need to convert the double jump caused by a nested
=switch= into a single jump. Each =case= label is associated to *one*
=integral= value. A double jump therefore requires *two* =integral=
values to dispatch. Therefore we need to

1. *convert* /two =integral= values into one =integral= value/, and

2. this must be done *at compile time* (since the value must be
   associated to a =case= label), and

3. we need to *convert back* /one =integral= value into two =integral=
   values/, and

4. this must also be done *at compile time* because we want to use the
   chosen integral values to perform /static/ dispatch (say, as
   =std::integral_constant= tags).

For this section we leave the compile time requirements aside and deal
with the converting to and back from one =integral= to two =integral=
values.


At this point whoever did some amount of math is already thinking
about a bijection between the natural numbers and the (binary)
Cartesian product of the natural numbers with themselves, also called
a [[https://en.wikipedia.org/wiki/Pairing_function][pairing function]]. And indeed that is where we are going but (1) we
cannot use any pairing if we want good code generation from the
compiler, and (2) I still want to give a rough overview for the
uninitiated in the matter of pairings.

** Some background on pairings

** Choosing a pairing

* The solution

* Beyond the solution: going variadic

* Conclusion
